@startchen
entity Missione {
  Codice
  Obbiettivo
  Stato
  DataFine
  DataInizio
}
entity Membro {
	Codice
	Nome
	Ruolo
}
entity Sensore {
	ID
	Posizione {
		Latitudine
		Longitudine
		Altitudine
		}
		tipo
		dataInstallazione
		ultimoControllo
		stato
}	
@endchen
